### ISSUE TITLE
Неверный лог после обновления оригинальной ветки

### ISSUE THREAD

**Issue by dsalahutdinov** [Le6ow5k1/greenhorn#1]
Когда подтягиваешь изменения
```bash
git pull --rebase upstream develop
```

и пушишь их в ветку своего форка, с которого отправлен ПР, бот учитывает эти обновления как твои https://github.com/abak-press/blizko/pull/9747#issuecomment-278879767

**Comment by Le6ow5k1** [comment]
хм, вроде фиксил эту проблему
на выходных погляжу и поправлю
